pipeline {
    agent any

    environment {
        IMAGE_NAME = "mern-hello-service"
        ECR_REGISTRY = "975050024946.dkr.ecr.ap-south-1.amazonaws.com"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Sadanki/SampleMERNwithMicroservices.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/helloService') {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Tag & Push to ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY"
                    sh "docker tag $IMAGE_NAME $ECR_REGISTRY/$IMAGE_NAME"
                    sh "docker push $ECR_REGISTRY/$IMAGE_NAME"
                }
            }
        }
    }
}
